---
- name: Check that a page returns successfully
  ansible.builtin.uri:
    url: http://{{ ansible_host }}
    follow_redirects: all
    status_code: [200, 403]
    method: GET
  register: _result
#  failed_when: this is failed or "'PAGE' not in this.content"

- name: Print var
  ansible.builtin.debug:
    var: _result.server
...
